---
TauTracks:
  - "TauTracks.nInnermostPixelHits"
  - "TauTracks.nPixelHits"
  - "TauTracks.nSCTHits"
  - "TauTracks.chargedScoreRNN"
  - "TauTracks.isolationScoreRNN"
  - "TauTracks.conversionScoreRNN"
  - "TauTracks.pt"
  - "TauTracks.dphiECal"
  - "TauTracks.detaECal"
  - "TauTracks.jetpt"
  - "TauTracks.d0TJVA"
  - "TauTracks.d0SigTJVA"
  - "TauTracks.z0sinthetaTJVA"
  - "TauTracks.z0sinthetaSigTJVA"

NeutralPFO:
  - "NeutralPFO.dphiECal"
  - "NeutralPFO.dphi"
  - "NeutralPFO.detaECal"
  - "NeutralPFO.deta"
  - "NeutralPFO.pt"
  - "NeutralPFO.jetpt"
  - "NeutralPFO.FIRST_ETA"
  - "NeutralPFO.SECOND_R"
  - "NeutralPFO.DELTA_THETA"
  - "NeutralPFO.CENTER_LAMBDA"
  - "NeutralPFO.LONGITUDINAL"
  - "NeutralPFO.SECOND_ENG_DENS"
  - "NeutralPFO.ENG_FRAC_CORE"
  - "NeutralPFO.NPosECells_EM1"
  - "NeutralPFO.NPosECells_EM2"
  - "NeutralPFO.energy_EM1"
  - "NeutralPFO.energy_EM2"
  - "NeutralPFO.EM1CoreFrac"
  - "NeutralPFO.firstEtaWRTClusterPosition_EM1"
  - "NeutralPFO.firstEtaWRTClusterPosition_EM2"
  - "NeutralPFO.secondEtaWRTClusterPosition_EM1"
  - "NeutralPFO.secondEtaWRTClusterPosition_EM2"

ShotPFO:
  - "ShotPFO.dphiECal"
  - "ShotPFO.dphi"
  - "ShotPFO.detaECal"
  - "ShotPFO.deta"
  - "ShotPFO.pt"
  - "ShotPFO.jetpt"

ConvTrack:
  - "ConvTracks.dphiECal"
  - "ConvTracks.dphi"
  - "ConvTracks.detaECal"
  - "ConvTracks.deta"
  - "ConvTracks.pt"
  - "ConvTracks.jetpt"
  - "ConvTracks.d0TJVA"
  - "ConvTracks.d0SigTJVA"
  - "ConvTracks.z0sinthetaTJVA"
  - "ConvTracks.z0sinthetaSigTJVA"

TauJets:
  - "TauJets.centFrac"
  - "TauJets.etOverPtLeadTrk"
  - "TauJets.dRmax"
  - "TauJets.SumPtTrkFrac"
  - "TauJets.ptRatioEflowApprox"
  - "TauJets.mEflowApprox"
  - "TauJets.ptJetSeed"
  - "TauJets.etaJetSeed"
  - "TauJets.phiJetSeed"

DecayMode: 
  - "TauJets.truthDecayMode"

TruthProng: 
  - "TauJets.truthProng"

AUX:
  - "TauJets.truthProng"
  - "TauJets.truthDecayMode"
  - "TauJets.mu"
  - "TauJets.ptJetSeed"
  - "TauJets.etaJetSeed"
  - "TauJets.phiJetSeed"
  - "TauJets.RNNJetScoreSigTrans"
  - "TauJets.mcEventWeight"